### ISSUE TITLE
Incorrect pin mappin on bluepill

### ISSUE THREAD

**Issue by eduardokenj** [passinglink/passinglink#2]
the mapping of inputs are incorrect beacuse bluepill use a STM103C8T6 don't have a PD and PC0 to PC12 ports

**Comment by jmgao** [comment]
Whoops, yeah, looks like I blindly copy pasted the pin configuration from my custom PCB that uses an STM32F103RET6. The robotdyn_f303 board config is also a copy paste of this, and it's pin compatible with the regular bluepill AFAIK, so it's also wrong.
