### ISSUE TITLE
Is there a way to choose mode (Ps3,Ps4,Switch) manually?

### ISSUE THREAD

**Issue by x0rtes** [passinglink/passinglink#29]
Is there a way to choose mode (Ps3,Ps4,Switch) manually? Like holding a specific button while connecting the USB?
Batocera recognizes my controller like 2 controllers for some reason, and I think this could be related to the output mode.
Using stm32.

Thanks in advance!

**Comment by jmgao** [comment]
Yeah, holding square/triangle/r1 will force switch/ps3/ps4 respectively: https://github.com/passinglink/passinglink/blob/master/src/output/usb/usb.cpp#L182
