### ISSUE TITLE
MicroDash PCB Pin layout to dts File Mapping

### ISSUE THREAD

**Issue by dASButten** [passinglink/passinglink#31]
Would like to know, what is mapping between microdash.dts pins and the ones in the ETA model? For instance, in microdash.dts file, does button_l1 map to p0_1 (6)?
![image](https://user-images.githubusercontent.com/115133385/194225883-7d30999c-76ac-4940-96fe-fb9faba21f86.png)

**Comment by jmgao** [comment]
No, the part on the right you have there is an LED driver.

`&gpio0 5` is P0.05 on the E73-2G4M08S1C NRF module.
